version: '2'

services:
  digdag:
    build:
      context: ./digdag
      dockerfile: Dockerfile
    restart: always
    ports:
      - "65432:65432"
      - "65433:65433"
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: digdag
      POSTGRES_PASSWORD: password
      POSTGRES_DB: digdag
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: digdag
      POSTGRES_PASSWORD: password
      POSTGRES_DB: digdag
    volumes:
      - ./db:/var/lib/postgres/data
